### ISSUE TITLE
Class Recs not found

### ISSUE THREAD

**Issue by brusoth09** [practical-recommender-systems/moviegeek#1]
views.py import from recommender.models import SeededRecs, Recs, MovieDescriptions, Similarity. But Recs class is not found in recommender/models.py class. So `python manage.py makemigrations` throws 

> ImportError: cannot import name Recs

**Comment by kimfalk** [comment]
Thank you for reporting an issue, I am afraid I had committed half a commit, to fix another bug. It should now be fixed, and running.
