### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by dmahler26** [practical-recommender-systems/moviegeek#10]
Working with a virtual environment running py 3.6 on windows 10. Trying to get the Django site working. Initially ran into an issue with requiring the API key to be in a file named '.prs' since this was not a valid filename. At least think I have managed to circumvent this by naming it differently and updating the script which raised the error (might be others I need to address as I go along?)

Anyways, after making that fix I now get the following error:

------------------------------
JSONDecodeError at /
Expecting value: line 1 column 23 (char 22)
Request Method:	GET
Request URL:	http://127.0.0.1:8001/
Django Version:	1.11
Exception Type:	JSONDecodeError
Exception Value:	
Expecting value: line 1 column 23 (char 22)
Exception Location:	C:\Users\<username>\Anaconda3\envs\prs\lib\json\decoder.py in raw_decode, line 357
Python Executable:	C:\Users\<username>\Anaconda3\envs\prs\python.exe
Python Version:	3.6.4
Python Path:	
['C:\\Users\\<username>\\Documents\\GitHub\\moviegeek',
 'C:\\Users\\<username>\\Anaconda3\\envs\\prs\\python36.zip',
 'C:\\Users\\<username>\\Anaconda3\\envs\\prs\\DLLs',
 'C:\\Users\\<username>\\Anaconda3\\envs\\prs\\lib',
 'C:\\Users\\<username>\\Anaconda3\\envs\\prs',
 'C:\\Users\\<username>\\Anaconda3\\envs\\prs\\lib\\site-packages']
Server time:	Fri, 9 Feb 2018 17:58:34 +0000

Environment:

Request Method: GET
Request URL: http://127.0.0.1:8001/

Django Version: 1.11
Python Version: 3.6.4
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django_extensions',
 'moviegeeks',
 'collector',
 'analytics',
 'recommender']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback:

File "C:\Users\<username>\Anaconda3\envs\prs\lib\json\decoder.py" in raw_decode
  355.             obj, end = self.scan_once(s, idx)

During handling of the above exception (22), another exception occurred:

File "C:\Users\<username>\Anaconda3\envs\prs\lib\site-packages\django\core\handlers\exception.py" in inner
  41.             response = get_response(request)

File "C:\Users\<username>\Anaconda3\envs\prs\lib\site-packages\django\core\handlers\base.py" in _legacy_get_response
  249.             response = self._get_response(request)

File "C:\Users\<username>\Anaconda3\envs\prs\lib\site-packages\django\core\handlers\base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "C:\Users\<username>\Anaconda3\envs\prs\lib\site-packages\django\core\handlers\base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "C:\Users\<username>\Anaconda3\envs\prs\lib\site-packages\django\utils\decorators.py" in _wrapped_view
  149.                     response = view_func(request, *args, **kwargs)

File "C:\Users\<username>\Documents\GitHub\moviegeek\moviegeeks\views.py" in index
  14.     api_key = get_api_key()

File "C:\Users\<username>\Documents\GitHub\moviegeek\moviegeeks\views.py" in get_api_key
  140.     cred = json.loads(open("prs_api_key").read())

File "C:\Users\<username>\Anaconda3\envs\prs\lib\json\__init__.py" in loads
  354.         return _default_decoder.decode(s)

File "C:\Users\<username>\Anaconda3\envs\prs\lib\json\decoder.py" in decode
  339.         obj, end = self.raw_decode(s, idx=_w(s, 0).end())

File "C:\Users\<username>\Anaconda3\envs\prs\lib\json\decoder.py" in raw_decode
  357.             raise JSONDecodeError("Expecting value", s, err.value) from None

Exception Type: JSONDecodeError at /
Exception Value: Expecting value: line 1 column 23 (char 22)
------------------------------

Any help would greatly appreciated!

**Comment by dmahler26** [comment]
Also, I had to install packages manually since neither conda nor pip could get through requirements.txt without encountering multiple errors with scipy, pyLDAvis, etc.

Here is a list of the installed packages - perhaps there is an incompatibility with a newer version I have installed?

-----
anaconda                  custom           py36h363777c_0
appdirs                   1.4.3                     <pip>
attrs                     17.4.0                    <pip>
boto                      2.46.1                    <pip>
boto3                     1.5.25                    <pip>
botocore                  1.8.39                    <pip>
bz2file                   0.98                      <pip>
bzip2                     1.0.6                    vc14_1  [vc14]  conda-forge
ca-certificates           2017.11.5                     0    conda-forge
certifi                   2018.1.18                 <pip>
certifi                   2017.11.5                py36_0    conda-forge
chardet                   3.0.4                     <pip>
colorama                  0.3.9                     <pip>
curl                      7.55.1                   vc14_0  [vc14]  conda-forge
cycler                    0.10.0                    <pip>
Django                    1.11                      <pip>
django-extensions         1.7.8                     <pip>
docutils                  0.14                      <pip>
freetype                  2.8.1                    vc14_0  [vc14]  conda-forge
funcy                     1.10                      <pip>
future                    0.16.0                    <pip>
gensim                    3.3.0                     <pip>
hdf5                      1.10.1                   vc14_1  [vc14]  conda-forge
icc_rt                    2017.0.4             h97af966_0
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.6                       <pip>
intel-openmp              2018.0.0             hd92c6cd_8
Jinja2                    2.10                      <pip>
jmespath                  0.9.3                     <pip>
joblib                    0.11                      <pip>
jpeg                      9b                       vc14_2  [vc14]  conda-forge
krb5                      1.14.2                   vc14_0  [vc14]  conda-forge
libiconv                  1.14                     vc14_4  [vc14]  conda-forge
libpng                    1.6.34                   vc14_0  [vc14]  conda-forge
libssh2                   1.8.0                    vc14_2  [vc14]  conda-forge
libtiff                   4.0.9                    vc14_0  [vc14]  conda-forge
libxml2                   2.9.5                    vc14_1  [vc14]  conda-forge
libxslt                   1.1.32                   vc14_0  [vc14]  conda-forge
lzo                       2.10                     vc14_0  [vc14]  conda-forge
MarkupSafe                1.0                       <pip>
matplotlib                2.1.2                     <pip>
mkl                       2018.0.1             h2108138_4
nltk                      3.2.5                     <pip>
numexpr                   2.6.4                     <pip>
numpy                     1.14.0                    <pip>
numpy                     1.12.1                    <pip>
numpy                     1.14.0           py36h4a99626_1
openssl                   1.0.2n                   vc14_0  [vc14]  conda-forge
packaging                 16.8                      <pip>
pandas                    0.22.0                    <pip>
pip                       9.0.1                    py36_1    conda-forge
pluggy                    0.6.0                     <pip>
psycopg2                  2.7.4                     <pip>
py                        1.5.2                     <pip>
pyLDAvis                  2.1.1                     <pip>
pyparsing                 2.2.0                     <pip>
pytest                    3.4.0                     <pip>
python                    3.6.4                         0    conda-forge
python-dateutil           2.6.1                     <pip>
pytz                      2017.2                    <pip>
qt                        5.6.2                    vc14_1  [vc14]  conda-forge
requests                  2.18.4                    <pip>
s3transfer                0.1.12                    <pip>
scikit-learn              0.19.1           py36h53aea1b_0
scipy                     1.0.0            py36h1260518_0
scipy                     1.0.0                     <pip>
setuptools                38.4.0                   py36_0    conda-forge
six                       1.10.0                    <pip>
smart-open                1.5.6                     <pip>
sqlite                    3.20.1                   vc14_2  [vc14]  conda-forge
stop-words                2015.2.23.1               <pip>
tk                        8.6.7                    vc14_0  [vc14]  conda-forge
urllib3                   1.22                      <pip>
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wheel                     0.30.0                   py36_2    conda-forge
wincertstore              0.2                      py36_0    conda-forge
winpty                    0.4.3                    vc14_2  [vc14]  conda-forge
yaml                      0.1.7                    vc14_0  [vc14]  conda-forge
zlib                      1.2.11                   vc14_0  [vc14]  conda-forge

**Comment by kimfalk** [comment]
Hi, 

Thank you for your feedback, it has been some time since I tested it on Windows. But as far as I can see you get an error because you have an '/' in your prs-file. The format of the file should be as follows:

{ "themoviedb_apikey": "THE_API_KEY" }

where THE_API_KEY should be exchanged with your api key. So there shouldnt be any '/'s in the file.

**Comment by dmahler26** [comment]
Thanks for the response - turns out I just left out the quotations around the API key (whoops...)

The page loads now but I seem to be encountering some other issues (no data, other errors on navigation). As much as I would like to get everything working I think I'll just do my best to proceed with looking through the code when necessary since I'd rather not lose too much time troubleshooting. From what I've gone through thus far the book seems to do a good job walking through the details without needing to see the site itself.

Appreciate the help!

**Comment by kimfalk** [comment]
Hi Dmahler26, 

If you have other issues, please open a new issue for each and I will do my best to help. 

Kim
