### ISSUE TITLE
Association rules not working

### ISSUE THREAD

**Issue by ozanpekmezci** [practical-recommender-systems/moviegeek#13]
I am using MacOS with Python 3.7. Before coming to the association rule problem, I had some issues with the installation instructions that I had to fix manually:

1. When I ran `pip3 install -r requirements.txt`, I got the error `Failed building wheel` for numpy, scipy and pandas. After that I tried installing the packages with the versions on `requirements.txt` manually. For example: `pip install numpy==1.12.1`, but received the same error messages. That's why I installed those packages with `pip install` and updated the entries in `requirements.txt`. Therefore, the versions I have for numpy, pandas and scipy are 1.15.4, 0.23.4 and 1.1.0 respectively.  

2. When I ran the command `python3 manage.py makemigrations`,  I got the error which is mentioned [here](https://stackoverflow.com/questions/48822571/syntaxerror-generator-expression-must-be-parenthezised-python-manage-py-migra). Apparently, Django 1.11 and Python 3.7 are incompatible and will never be. Therefore I installed the Django version 2.1.3. 

3. Because of the Django version, I had to change `MIDDLEWARE_CLASSES` in `settings.py` to `MIDDLEWARE` and remove `django.contrib.auth.middleware.SessionAuthenticationMiddleware`. 

4. At this point, I was able to run the website. The real problem is that, I never see recommendations on the main page or under movies on details pages. I populated the database with logs, "bought" many movies etc. but still receive no recommendations and the terminal always show `recs from association rules: []`

Why do you think, it's not working and what can I do? Maybe you should also try running the project on a clean environment for the other problems that I mentioned before. Congrats on the book and project though. 

Edit: Btw forgot to mention that I tried this on two different environments. One created by virtualenv and second by conda.

**Comment by kimfalk** [comment]
Thank you for your comments. I have not tried it with Python 3.7; it runs fine on python 3.6.5, I tested that a few weeks ago. Will have a look at the errors.  

Did you read chapter 5 of the book? It describes the steps to make the association rules produce recs.

**Comment by ozanpekmezci** [comment]
Hi, thanks for the response. I checked chapter 5, which mentioned running `populate_logs` script and `builder.association_rules_calculator`. So I ran them again and still have no recommendations on the homepage.

**Comment by kimfalk** [comment]
Hi, 
Updated the requirements and settings which should solve the problems you indicated above. It is running fine on python 3.7 now. 

Regarding not seeing any association rules, I have made the populate_logs add more log data and lowered the minimum support that is needed for a rule to be saved. If you rerun it and click on one of the movies in the chart to the right you should see recs based on association rules. To see recs on the front page, you need to be buying movies which are in the association rules. The populate_logs has some lists of movies that it uses. The movies in lists are getting a bit dated, so I will update that one of these days, for now, you can try adding some ids yourself.

**Comment by ozanpekmezci** [comment]
It worked, thanks. I ran everything from scratch and the only change I needed to make was increasing the maximum length of the field `movie_id` from the model `Rating` from 8 to 16. It threw an error while populating logs. Maybe you'd like to change it. Thanks again!

**Comment by kimfalk** [comment]
Thanks, I have been updating the max length on the models. But I guess I missed one. Odd, that I managed to populate everything without error. In any case, it is now updated as well.
