### ISSUE TITLE
Windows - Unable to create .prs file

### ISSUE THREAD

**Issue by magnus-sigurdsson** [practical-recommender-systems/moviegeek#17]
A part of the installation instruction is:

create a file in the root of the directory called ".prs" and add { "themoviedb_apikey": <INSERT YOUR APIKEY HERE>}. (remember to remove the "<" and ">")

Windows is unable to create a file without a filename, throws the following error "You must type a file name.".

Is there a workaround to provide the API key without a ".prs" file?

**Comment by kimfalk** [comment]
You can create a .prs file by going to command prompt, cd to the appropriate folder and type:

notepad .prs

After confirmation dialog the file will be created and you will be editing it directly.

**Comment by Shivhari99** [comment]
how to open .prs and add {"themoviedb_apikey":}Remember to delete "<" and ">". After finishing, the content of the file should be similar to {"themoviedb_apikey":"6d88c9a24b1bc9a60b374d3fe2cd92ac"}

**Comment by Shivhari99** [comment]
I'm little bit confused, I made the .prs file in the notepad format and then tried to run manage.py on server 8001, but server hangs and shows system identified 9 issues (0 silenced).
