### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by syuhung** [practical-recommender-systems/moviegeek#19]
hi,when i open http://127.0.0.1:8000/analytics/user/400001/,i can only see the data in (movie Rate) and (recent Log).There is no data in (Taste) and (Personalised recommendations).it tell me FileNotFoundError: [Errno 2] No such file or directory: './models/bpr/item_bias.data' when i look the console,how can i solve this problem?

**Comment by kimfalk** [comment]
Hi, 

Did you follow the install instructions in the README.md file? You should do that and then additionally run the following command

```
python3 -m builder.implicit_ratings_calculator
```

The script will calculate implicit ratings based on user behavior on the site ( the user you are looking at (user_id: 40001) is created with the `populate_logs.py`, which only populates logs). 

This problem with the missing file should not occur. I'm adding a check to see if models are built, before trying to calculate recs. To build the model check out Chapter 13 of the book
