### ISSUE TITLE
No such file or directoryNo 

### ISSUE THREAD

**Issue by miladfa7** [practical-recommender-systems/moviegeek#21]
**sudo python3 populate_ratings_from_MovieLens_data.py**

File "populate_ratings_from_MovieLens_data.py", line 56, in <module>
    populate('/Users/u0157492/Downloads/ml-latest-small/ratings.csv')
  File "populate_ratings_from_MovieLens_data.py", line 30, in populate
    with open(path, newline='') as csvfile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/u0157492/Downloads/ml-latest-small/ratings.csv'

**Comment by kimfalk** [comment]
Did you download the movielens data?
