### ISSUE TITLE
create api 

### ISSUE THREAD

**Issue by xudongMk** [practical-recommender-systems/moviegeek#31]
what should i type on  'Application URL' and 'Application Name' option？

**Comment by kimfalk** [comment]
I'm not sure which 'Application URL' and 'Application Name' you are referring to? Could you explain better whats the issue

**Comment by xudongMk** [comment]
> I'm not sure which 'Application URL' and 'Application Name' you are referring to? Could you explain better whats the issue

i solved this problem already~~~~tks

**Comment by xudongMk** [comment]
> I'm not sure which 'Application URL' and 'Application Name' you are referring to? Could you explain better whats the issue

i solved this problem already~~~~tks
