### ISSUE TITLE
Movie are not getting recommended

### ISSUE THREAD

**Issue by saa-d** [practical-recommender-systems/moviegeek#33]
I cloned the repo, installed PostgreSQL, configured settings.py to point at my PSQL installation, setup a TMDb API key and added the key with the appropriate format into a new .prs file.

I did "makemigrations" and "migrate --run-syncdb", both of them went through successfully, I even double checked through pgAdmin and all of the tables were created successfully.

Afterwards I ran "populate_moviegeek.py", the script threw out an error due to a size difference between one of the columns in the dataset and the DB, thus I resorted to use the 100K version of the MovieTweetings dataset, I copied the URL and pasted it as the default parameter for the download_movies function, and rerun the script, everything went through beautifully! All of the movies were added into the Database successfully. 

Since I got the 100K version of the MovieTweetings Dataset, I also got the ratings for them, changed the URL inside "populate_ratings.py" and ran the script, everything worked here as well.

Last but not least I ran "populate_logs.py" and it worked as well.

Finally I ran the server using "python manage.py runserver" and I tried accessing the webpage, no issues here, however!
No recommendations were being shown! The analytics page didn't work at all! The console showed diffferent kinds of errors, and I tried getting into the details page of a movie maybe I would get a "Movies similar to ..." recommendations, but didn't aswell.

All in all, I am desperately trying to get the script to work but I can't! 

@kimfalk your help would be greatly appreciated!

My current python version: 3.7.7
Windows 10 Pro x64
All of the packages installed successfully using "pip install -r requirements.txt"

**Comment by kimfalk** [comment]
Hi Saad Sawash, 

This site is described in the book Practical Recommender Systems, you should refer to that. But if you are looking to make the recommendations work have a look in the builder folder where all the algorithms for recommendations are. 

The scripts to get the movietweetings should be working though so I will have a look at that.

**Comment by saa-d** [comment]
Thanks for the quick resposne @kimfalk 

I actually have bought your book, but still haven't started reading through it, I wanted to test out the website and see the recommendations in action before diving in.

Waiting for your update on the MovieTweetings issue.
