### ISSUE TITLE
Movies are Not Recommending by the site

### ISSUE THREAD

**Issue by HassanAbbas7357** [practical-recommender-systems/moviegeek#34]
Every thing is working fine but the site is not recommending movies i bought some movies and it shows on analytics page that i bought movies and the status are in cluster is showing NO
its capturing my moves but not recommending movies

**Comment by kimfalk** [comment]
Hi, 

I'm happy everything is working, usually, that is not the case when people post issues :). Have you run the scripts in the builder folder as described in the book?

**Comment by HassanAbbas7357** [comment]
Sorry i couldn't run the scripts I'll try and let you know if its working

**Comment by HassanAbbas7357** [comment]
Sir i want another favour please:
I want to build a movie recommender which can only recommends movies on
plot description/overview based using word embeddings like if i give model
a movie name it will recommend the most similar movies based on thier
description how can i build this? Can you please sepcify the path
I tried the cosine way using aTFidf i want the same results with any lite
model can i do this with LDA but how many topics and parameters should i
choose? Because iam using a 27k movies dataset kindly reply must

**Comment by kimfalk** [comment]
Dear sir, 

This code is used in my book _Practical Recommender Systems_, I recommend reading ch 10 in my book, which is about content-based filtering.  

The book can be bought here: [manning.com](https://www.manning.com/books/practical-recommender-systems?a_aid=prs&a_bid=1b90f749)

**Comment by HassanAbbas7357** [comment]
Ok sir thanks
