### ISSUE TITLE
Code documentation

### ISSUE THREAD

**Issue by pbamotra** [practical-recommender-systems/moviegeek#5]
I previewed the book on Manning and it seems to be good read. The accompanied code is however not well documented -- missing comments, docstrings etc. I recommend the author to please spend time in doing the same. 

Thanks

**Comment by kimfalk** [comment]
Hi,

Sorry for the late replay, having been keeping up with issues, and thank you for your comment. The code could be better commented no doubt about that. But remember it is the recommender system part which is important not the Django site part. I recommend having a look at the [How to Tango With Django](https://github.com/leifos/tango_with_django) code for better description on how to use Django. 

If you have some concrete examples where the code is confusing and not described in the book. Please let me know.
