### ISSUE TITLE
TMDB has closed the app directory

### ISSUE THREAD

**Issue by srinivas-sateesh** [practical-recommender-systems/moviegeek#61]
Hey @kimfalk, 

Awesome book on PRS. Thank you!!. 

I was bring up your PRS and registered on TMDB. They are not allowing to create files in App Directory now and we get the File not found error. Kindly provide a work around. Thank you

![image](https://user-images.githubusercontent.com/10737892/166301816-832eb413-6f28-4af5-82ed-bf1a98c930ac.png)

**Comment by kimfalk** [comment]
Hi @srinivas-sateesh,

Thank you for your kind words. Im not sure why you want to create a file in their API directory. if you are referring to the `.prs` file, then you should create it in the folder where you have cloned the repository.

**Comment by srinivas-sateesh** [comment]
Oh ok.. Let me check. I must have misunderstood. Thanks for clarifying.
