### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by luc1dd** [practical-recommender-systems/moviegeek#8]
```
/Projects/moviegeek/recommender/views.py", line 167
    print(f"lda loaded in {datetime.now()-start_time}")
                                                     ^
```
SyntaxError: invalid syntax

**Comment by kimfalk** [comment]
Hi,

Sorry for the late replay, having been keeping up with issues. 

Could you tell me which python version you are running on. It is suppose to be legal Python 3.6 code. Have a look at the following blogpost: https://cito.github.io/blog/f-strings/
